server:
  port: 8083

spring:
  application:
    name: training-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ldms_training
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/