server:
  port: 8084

spring:
  application:
    name: progress-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ldms_progress
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/