server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/learnsphere
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your-256-bit-secret
  expiration: 86400000 # 24 hours

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/