server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/api/feedback/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/